name: Scheduled Telegram RSS Bot

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  run_bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Use a modern, stable Python version
          python-version: '3.10' 

      - name: Install dependencies (FORCED UPDATE)
        run: |
          # The error occurs because the installed version is too old.
          # We explicitly install a recent, known-compatible version (e.g., v20.x or latest)
          # using --upgrade to bypass any cached old version.
          pip install --upgrade feedparser requests beautifulsoup4 python-telegram-bot

      - name: Run Bot Script
        # Executes your Python file: bot.py
        run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
          
      - name: Commit and Push Cache File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 [Bot] Update posted.json cache'
          files: posted.json
